management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      enabled: true
      show-details: always
    shutdown:
      enabled: true
  tracing:
    enabled: true
    sampling:
      probability: 1.0
    zipkin:
      tracing:
        endpoint: http://${ZIPKIN_HOST:localhost}:9411/api/v2/spans
info:
  env:
    enabled: true

queue:
  movie:
    name: movie-queue
  serie:
    name: serie-queue
  catalog:
    name: catalog-queue

spring:
  rabbitmq:
    host: ${RABIT_HOST:localhost}
    port: 5672
    username: guest
    password: guest
