server:
  port: 8090

spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "Access-Control-Allow-Headers, Content-Type, Access-Control-Allow-Headers, Authorization, X-Requested-With"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS

      routes:
        - id: ms-movie
          uri: lb://movie-service
          predicates:
            - Path=/movies/**
          filters:
            - name: CircuitBreaker
              args:
                name: breaker-backend
                fallbackUri: forward:/fallback

        - id: ms-catalog
          uri: lb://catalog-service
          predicates:
            - Path=/catalogs/**
          filters:
            - name: CircuitBreaker
              args:
                name: breaker-backend
                fallbackUri: forward:/fallback

        - id: ms-serie
          uri: lb://serie-service
          predicates:
            - Path=/series/**
          filters:
            - name: CircuitBreaker
              args:
                name: breaker-backend
                fallbackUri: forward:/fallback

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka
